# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quantum Biosystems
title-bar: Quantum Biosystems,クオンタムバイオシステムズ｜超高速DNAシークエンサー開発
email: info@quantumbiosystems.com
description: >- # this means to ignore newlines until "baseurl:"
        Quantum Biosystems Inc.
        Quantum Sequencing Application of quantum mechanics to the development of innovative single-molecule DNA sequencers and genome alignment analytics platform
        クオンタムバイオシステムズ株式会社 最先端研究開発支援プログラム(FIRST)の研究成果を中心とした、DNAシークエンサー、及び、ゲノム配列解析プラットフォームの開発
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: quantumbio
#github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

collections:
  features:
    output: true
    permalink: /features/:path/
  about:
    output: true
    permalink: /about/:path/
  get_involved:
    output: true
    permalink: /get_involved/:path/
  redirects:
    output: true
    permalink: /redirects/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
